const personnelData = [
  // Elkasista
{ "nama": "Serka Ahmad Saputra Surna", "prodi": "Elkasista" },
{ "nama": "Sertu Ito Suryo Purnomo", "prodi": "Elkasista" },
{ "nama": "Sertu Djoko lman Santoso", "prodi": "Elkasista" },
{ "nama": "Sertu M. Nur Alvyangga", "prodi": "Elkasista" },
{ "nama": "Sertu Anggit Priaji Susilo", "prodi": "Elkasista" },
{ "nama": "Serka Pradana Bagoes", "prodi": "Elkasista" },
{ "nama": "Sertu R.H. Eka Anggara", "prodi": "Elkasista" },
{ "nama": "Sertu Ganang Aji Pamungkas", "prodi": "Elkasista" },
{ "nama": "Sertu Dwi Wahyu Wicaksono", "prodi": "Elkasista" },
{ "nama": "Sertu Dwi Heri Kiswanto", "prodi": "Elkasista" },
{ "nama": "Sertu Putra Dwi Wicaksana", "prodi": "Elkasista" },
{ "nama": "Sertu Nizar Rizki S. R.", "prodi": "Elkasista" },
{ "nama": "Sertu Sandy Eka Sakti Prasetyo", "prodi": "Elkasista" },
{ "nama": "Sertu M. Ridhona Perwira", "prodi": "Elkasista" },
{ "nama": "Sertu Badrus Soleh", "prodi": "Elkasista" },
{ "nama": "Sertu Prya Agus Setyabudi", "prodi": "Elkasista" },
{ "nama": "Sertu Denny Heryawan", "prodi": "Elkasista" },
{ "nama": "Sertu Sofyan Dwi Jayanto", "prodi": "Elkasista" },
{ "nama": "Sertu Fathul Ulum", "prodi": "Elkasista" },
{ "nama": "Sertu Febriyantoro", "prodi": "Elkasista" },

  // Otoranpur
{ "nama": "Serka Abdul Gani", "prodi": "Otoranpur" },
{ "nama": "Sertu Alfendi Sumarto", "prodi": "Otoranpur" },
{ "nama": "Serka Imam Awaludin Mubarok", "prodi": "Otoranpur" },
{ "nama": "Sertu M. Rizky Jambak", "prodi": "Otoranpur" },
{ "nama": "Sertu Anggi Bagus Bastiyan", "prodi": "Otoranpur" },
{ "nama": "Sertu Gregorius Veven", "prodi": "Otoranpur" },
{ "nama": "Sertu Fajar Imani R.", "prodi": "Otoranpur" },
{ "nama": "Sertu Hadi Iswanto", "prodi": "Otoranpur" },
{ "nama": "Sertu Gandung Tri Saputro", "prodi": "Otoranpur" },
{ "nama": "Sertu M. Fatur Rahman G.", "prodi": "Otoranpur" },
{ "nama": "Sertu Ali Prastyo Putra S.", "prodi": "Otoranpur" },
{ "nama": "Sertu Rizky Prasetio", "prodi": "Otoranpur" },
{ "nama": "Sertu Al Muhajar", "prodi": "Otoranpur" },
{ "nama": "Sertu Indra Hafidz", "prodi": "Otoranpur" },
{ "nama": "Sertu Nicolas Octa", "prodi": "Otoranpur" },
{ "nama": "Sertu Sasmito", "prodi": "Otoranpur" },
{ "nama": "Sertu Yohanes Uwa Jua", "prodi": "Otoranpur" },
{ "nama": "Sertu M. Rafaid", "prodi": "Otoranpur" },
{ "nama": "Sertu Rinaldo Waimbo", "prodi": "Otoranpur" },
{ "nama": "Sertu Mamaris Alpaha", "prodi": "Otoranpur" },

  // Rekamsiber
{ "nama": "Serka Rafles Manurung", "prodi": "Rekamsiber" },
{ "nama": "Sertu Khoirul Imam", "prodi": "Rekamsiber" },
{ "nama": "Sertu Hantok Panji", "prodi": "Rekamsiber" },
{ "nama": "Sertu Asep Yogi Istianto", "prodi": "Rekamsiber" },
{ "nama": "Sertu Darmawan Dwi", "prodi": "Rekamsiber" },
{ "nama": "Sertu Nova Disjayanto", "prodi": "Rekamsiber" },
{ "nama": "Sertu M. Rizkqi Firdauzi", "prodi": "Rekamsiber" },
{ "nama": "Sertu Gandi Rahmad", "prodi": "Rekamsiber" },
{ "nama": "Sertu Aditiya Fajrin", "prodi": "Rekamsiber" },
{ "nama": "Sertu M. Rahardian", "prodi": "Rekamsiber" },
{ "nama": "Sertu Ahmad Iwan", "prodi": "Rekamsiber" },
{ "nama": "Sertu Agung Nugroho", "prodi": "Rekamsiber" },
{ "nama": "Sertu Agung Nasution", "prodi": "Rekamsiber" },
{ "nama": "Sertu AlIdino Allban", "prodi": "Rekamsiber" },
{ "nama": "Sertu Wirpan Atmaja", "prodi": "Rekamsiber" },
{ "nama": "Sertu Dadi Prasetiya Budi", "prodi": "Rekamsiber" },
{ "nama": "Sertu Riski Hanafi", "prodi": "Rekamsiber" },
{ "nama": "Sertu Bagus Patria", "prodi": "Rekamsiber" },
{ "nama": "Sertu Adi Permadi", "prodi": "Rekamsiber" },

  // Telkommil
{ "nama": "Serka Rezky Mochamad Akbar", "prodi": "Telkommil" },
{ "nama": "Sertu Arjun Prayudha", "prodi": "Telkommil" },
{ "nama": "Sertu M. Andryan Prabowo", "prodi": "Telkommil" },
{ "nama": "Sertu Egidus Tefa", "prodi": "Telkommil" },
{ "nama": "Sertu Aditya Putra Pratama", "prodi": "Telkommil" },
{ "nama": "Sertu Septian Dwi Maulana", "prodi": "Telkommil" },
{ "nama": "Sertu Aliffian Harista", "prodi": "Telkommil" },
{ "nama": "Sertu Choirul Himawan", "prodi": "Telkommil" },
{ "nama": "Sertu Arif Purnomo", "prodi": "Telkommil" },
{ "nama": "Sertu Bambang Eko Sutikno", "prodi": "Telkommil" },
{ "nama": "Sertu Ardiansyah Dwi Saputra", "prodi": "Telkommil" },
{ "nama": "Sertu Wahyu Pranata", "prodi": "Telkommil" },
{ "nama": "Sertu Tony Fajar Setiawan", "prodi": "Telkommil" },
{ "nama": "Sertu Fauzan", "prodi": "Telkommil" },
{ "nama": "Sertu Moch. Alif Wellyanto", "prodi": "Telkommil" },
{ "nama": "Sertu Yossy Tamara Putra", "prodi": "Telkommil" },
{ "nama": "Sertu Dicky Dwi Ariyanto", "prodi": "Telkommil" },
{ "nama": "Sertu La Heri", "prodi": "Telkommil" },
{ "nama": "Serka Lisantino Prasetya", "prodi": "Telkommil" },
{ "nama": "Sertu Aldo Kolabie", "prodi": "Telkommil" },

  // Terasenmil
{ "nama": "Serka Benhard Bastian", "prodi": "Terasenmil" },
{ "nama": "Sertu Septriono Yudha T.", "prodi": "Terasenmil" },
{ "nama": "Sertu Adimas Prayogi H.", "prodi": "Terasenmil" },
{ "nama": "Sertu Ade Nurtachrudin", "prodi": "Terasenmil" },
{ "nama": "Serka Ferry Kurnia Sandi", "prodi": "Terasenmil" },
{ "nama": "Sertu Arif Rahmansyah", "prodi": "Terasenmil" },
{ "nama": "Sertu Syafruddin", "prodi": "Terasenmil" },
{ "nama": "Sertu Yenri Nur Ifan", "prodi": "Terasenmil" },
{ "nama": "Sertu Hendra Saputra", "prodi": "Terasenmil" },
{ "nama": "Sertu Ilham Romdhoni", "prodi": "Terasenmil" },
{ "nama": "Sertu Steven Elokpere", "prodi": "Terasenmil" },
{ "nama": "Sertu Kusnanto", "prodi": "Terasenmil" },
{ "nama": "Sertu Sukma Imam Nur", "prodi": "Terasenmil" },
{ "nama": "Sertu Fachrie Taufik R.", "prodi": "Terasenmil" },
{ "nama": "Sertu M. Nur Faizin", "prodi": "Terasenmil" },
{ "nama": "Sertu Andreas Afandi", "prodi": "Terasenmil" },
{ "nama": "Sertu Elsa Erwinsa", "prodi": "Terasenmil" },
{ "nama": "Sertu Zulbasyir Rahman", "prodi": "Terasenmil" },
{ "nama": "Sertu M. Zulfikar M", "prodi": "Terasenmil" },
{ "nama": "Sertu Reky Somantri", "prodi": "Terasenmil" }
];

